<span style="float:right"><a href="http://moldesign.bionano.autodesk.com/" target="_blank" title="About">About</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://forum.bionano.autodesk.com/c/Molecular-Design-Toolkit" target="_blank" title="Forum">Forum</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/autodesk/molecular-design-toolkit/issues" target="_blank" title="Issues">Issues</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://bionano.autodesk.com/MolecularDesignToolkit/explore.html" target="_blank" title="Tutorials">Tutorials</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://autodesk.github.io/molecular-design-toolkit/" target="_blank" title="Documentation">Documentation</a></span>
</span>
![Molecular Design Toolkit](img/Top.png)


<center><h1>Example 6: Align Two Molecules </h1> </center>
---


This notebook reads in two structures and calculates the transformation matrix aligning the C-alpha atoms from a subset of residues one structure to the other.

 - _Author_: [Dave Parker](https://github.com/ktbolt), Autodesk Research<br>
 - _Created on_: August 23, 2017
 - _Tags_: align, fit




In [70]:
import moldesign as mdt
from moldesign import units as u
from moldesign.molecules.atomcollections import AtomList
import numpy as np

## Read in and display the source molecule.

In [71]:
src_mol = mdt.from_pdb("1yu8")
src_mol.draw()

## Extract the source molecule C-alpha atoms for residues 64-72.

In [89]:
src_residues = src_mol.chains["X"].residues
src_residue_ids = set(range(64,73))
src_atoms = [res.atoms["CA"] for res in src_residues if res.pdbindex in src_residue_ids]
src_atoms_list = AtomList(src_atoms)

## Read in and display the destination molecule.

In [76]:
dst_mol = mdt.from_pdb("3ac2")
dst_mol.draw()

## Extract the destination molecule C-alpha atoms for residues 446-454.

In [77]:
dst_residues = dst_mol.chains["A"].residues
dst_residue_ids = set(range(446,455))
dst_atoms = [res.atoms["CA"] for res in residues if res.pdbindex in residue_ids]
dst_atoms_list = AtomList(dst_atoms)

## Calculate the transformation aligning the source atoms to destination atoms.

In [88]:
rmsd, xform = src_atoms_list.align(dst_atoms_list)
print("rmsd = %f" % rmsd)
print("transformation = \n" + np.array_str(xform))

rmsd = 0.412441
transformation = 
[[  1.00000000e+00   4.56737751e-16   2.21965480e-16  -7.10542736e-15]
 [ -3.52269708e-16   1.00000000e+00  -6.83377612e-17   8.88178420e-15]
 [ -4.55009138e-16   5.86301682e-16   1.00000000e+00   8.88178420e-15]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


## Transform all of the source atoms.

In [79]:
src_atoms = src_mol.atoms
coords = np.array([0.0, 0.0, 0.0, 1.0],dtype=float)

for i in range(0,len(src_atoms)):
    coords[0:3] = src_atoms[i].position.value_in(u.angstrom)
    xcoords = xform.dot(coords)
    src_atoms[i].x = xcoords[0] * u.angstrom
    src_atoms[i].y = xcoords[1] * u.angstrom
    src_atoms[i].z = xcoords[2] * u.angstrom


## Merge the source and destination molecules into s single molecule and display it.

In [80]:
merged_mol = mdt.Molecule([src_mol, dst_mol])
merged_mol.draw()